SELECT
    DATE_TRUNC('MONTH', TO_DATE(DATA, 'DD/MM/YYYY')) AS LUNA,
    SUM(SALARIU_BRUT) AS SALARIU_BRUT_TOTAL
FROM {{ ref('Salaries_model') }}
GROUP BY DATE_TRUNC('MONTH', TO_DATE(DATA, 'DD/MM/YYYY'))
ORDER BY DATE_TRUNC('MONTH', TO_DATE(DATA, 'DD/MM/YYYY'))