SELECT
    DATE_TRUNC('MONTH', TO_DATE(START_DATE, 'DD/MM/YYYY')) AS month_start,
    VACATION_TYPE,
    SUM(DATEDIFF(
        'day',
        TO_DATE(START_DATE, 'DD/MM/YYYY'),
        TO_DATE(END_DATE, 'DD/MM/YYYY')
    ) + 1) AS total_days
FROM Vacation_model
WHERE VACATION_TYPE IS NOT NULL
GROUP BY month_start, VACATION_TYPE
ORDER BY month_start, VACATION_TYPE
