SELECT 
    EMAIL_ADDRESS,
    TO_DATE(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS') AS TIMESTAMP,
    TO_DATE(START_DATE, 'DD/MM/YYYY') AS START_DATE,
    TO_DATE(START_DATE, 'DD/MM/YYYY') - TO_DATE(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS') AS LEAD_TIME,
FROM {{ref('Vacation_model')}}
WHERE VACATION_CANCELLED IS NULL
