SELECT 
    TO_CHAR(TO_DATE("START DATE", 'DD/MM/YYYY'), 'MM/YYYY') AS LUNA,
    "VACATION TYPE",
    COUNT(*) AS NUMAR_CONCEDII
FROM {{ref('Vacation_model')}}
WHERE "VACATION CANCELLED?" IS NULL
GROUP BY TO_CHAR(TO_DATE("START DATE", 'DD/MM/YYYY'), 'MM/YYYY'), "VACATION TYPE"
ORDER BY LUNA, "VACATION TYPE"
