with Vacation as (
    select 
    "END DATE" as END_DATE,
    "TIMESTAMP" as TIMESTAMP,
    "START DATE" as START_DATE,
    "BONUS PAYMENT" as BONUS_PAYMENT,
    "EMAIL ADDRESS" as EMAIL_ADDRESS,
    "VACATION TYPE" as VACATION_TYPE,
    "VACATION CANCELLED?" as VACATION_CANCELLED

    from {{ source('sursa_snowflake', 'VACATION_RESPONSES') }}
)

select END_DATE,TIMESTAMP,START_DATE,BONUS_PAYMENT,EMAIL_ADDRESS,VACATION_TYPE,VACATION_CANCELLED
from Vacation