SELECT 
    TO_CHAR(TO_DATE(DATA, 'DD/MM/YYYY'), 'MM/YYYY') AS LUNA,
    SUM("BONUS CONCEDIU") AS BONUS_CONCEDIU_TOTAL
FROM Salaries_model
GROUP BY TO_CHAR(TO_DATE(DATA, 'DD/MM/YYYY'), 'MM/YYYY')
ORDER BY TO_DATE('01/' || TO_CHAR(TO_DATE(DATA, 'DD/MM/YYYY'), 'MM/YYYY'), 'DD/MM/YYYY')