SELECT 
    TO_CHAR(TO_DATE("START DATE", 'DD/MM/YYYY'), 'MM/YYYY') AS LUNA,
    SUM(TO_DATE("END DATE", 'DD/MM/YYYY') - TO_DATE("START DATE", 'DD/MM/YYYY') + 1) AS ZILE_CONCEDIU
FROM Vacation_model
WHERE "VACATION CANCELLED?" IS NULL
GROUP BY TO_CHAR(TO_DATE("START DATE", 'DD/MM/YYYY'), 'MM/YYYY')
ORDER BY LUNA