SELECT 
    "EMAIL ADDRESS",
    TO_DATE(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS') AS TIMESTAMP,
    TO_DATE("START DATE", 'DD/MM/YYYY') AS START_DATE,
    TO_DATE("START DATE", 'DD/MM/YYYY') - TO_DATE(TIMESTAMP, 'DD/MM/YYYY HH24:MI:SS') AS LEAD_TIME,
FROM {{ source('sursa_modele', 'Vacation_model') }}
WHERE "VACATION CANCELLED?" IS NULL
