SELECT
    DATE_TRUNC('MONTH', TO_DATE(DATA, 'DD/MM/YYYY')) AS LUNA,
    SUM("BONUS CONCEDIU") AS BONUS_CONCEDIU_TOTAL
FROM {{ ref('Salaries_model') }}
GROUP BY DATE_TRUNC('MONTH', TO_DATE(DATA, 'DD/MM/YYYY'))
ORDER BY DATE_TRUNC('MONTH', TO_DATE(DATA, 'DD/MM/YYYY'))