with Vacation as (
    select ("END DATE","TIMESTAMP","START DATE","BONUS PAYMENT","EMAIL ADDRESS","VACANTION TYPE","VACATION CANCELLED?")

    from {{ source('sursa_snowflake', 'VACATION_RESPONSES') }}
)

select ("END DATE","TIMESTAMP","START DATE","BONUS PAYMENT","EMAIL ADDRESS","VACANTION TYPE","VACATION CANCELLED?")
from Vacation